Repository Team-BUNT/ClassManager, pull requests merged in 2022-10, with the labels that each got.

#7 EnrollmentListView와 Firebase Listener를 연동
  ClassManager/Model/Enrollment.swift
  ClassManager/View/ClassCalendarView.swift
  ClassManager/View/EnrollmentListView.swift
Labels: enhancement

#10 [FIX] timestamp logic of Enrollment model, view
  ClassManager/Model/Enrollment.swift
  ClassManager/View/EnrollmentListView.swift
Labels: bug

#15 Feature/class calendar view UI fix
  ClassManager/Assets.xcassets/Toast.colorset/Contents.json
  ClassManager/Reusable/ClassInfoBox.swift
  ClassManager/Reusable/Toast.swift
  ClassManager/View/ClassCalendarView.swift
Labels: 🎨 UI, 🧑🏻‍💻 안토니

#16 EnrollmentListView UI 및 sorting 수정
  ClassManager/Model/Enrollment.swift
  ClassManager/View/EnrollmentListView.swift
Labels: 🛠 Refactor, 🎨 UI, 🧑🏻‍💻 건

#18 클래스 추가 화면에서 사용자 경험 개선
  ClassManager.xcodeproj/xcshareddata/xcschemes/ClassManager.xcscheme
  ClassManager/Helper/DataService.swift
  ClassManager/View/AddClassView.swift
  ClassManager/View/ClassCalendarView.swift
Labels: 🌐 API, 🎨 UI, 🧑🏻‍💻 안토니, 📎 UX

#20 [HOTFIX]: EnrollmentListView에서 디자인 수정 반영
  ClassManager/View/EnrollmentListView.swift
Labels: 🔥 Hotfix

#21 [FIX] change present style sheet to full sheet
  ClassManager/View/ClassCalendarView.swift
Labels: 🐛 Debug
