Repository Team-BUNT/ClassManager, pull requests merged in 2022-11, with the labels that each got.

#31 휴강 관련 뷰 추가, 기능 구현
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Helper/Constant.swift
  ClassManager/Helper/DataService.swift
  ClassManager/Model/SuspendedClass.swift
  ClassManager/Model/SuspendedClasses.swift
  ClassManager/Reusable/ClassInfoBox.swift
  ClassManager/View/AttendanceView.swift
  ClassManager/View/ClassCalendarView.swift
  ClassManager/View/SuspendView.swift
Labels: 🌐 API, ⚙ feature, 🗃 Model, 🛠 Refactor, 🎨 UI, 🧑🏻‍💻 지오

#32 클래스 추가 뷰 수정/클래스 수정 뷰 추가
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Extensions/View.swift
  ClassManager/Helper/Constant.swift
  ClassManager/Helper/DataService.swift
  ClassManager/Model/Class.swift
  ClassManager/Reusable/ClassInfoBox.swift
  ClassManager/View/AddClassView.swift
  ClassManager/View/AttendanceView.swift
  ClassManager/View/EditClassView.swift
  ClassManager/View/EnrollmentListView.swift
Labels: 🌐 API, ⚙ feature, 🎨 UI, 🧑🏻‍💻 지오

#33 결제 현황 뷰 UI 구현 및 Firebase 연동
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Extensions/Font.swift
  ClassManager/Font/Montserrat-Regular.ttf
  ClassManager/Helper/DataService.swift
  ClassManager/Info.plist
  ClassManager/Model/Enrollment.swift
  ClassManager/Model/Student.swift
  ClassManager/View/CustomSearchBar.swift
  ClassManager/View/PaymentStatusView.swift
Labels: 🌐 API, ⚙ feature, 🎨 UI, 🧑🏻‍💻 건

#34 StudentInfoView 구현 및 TabView 연결
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Assets.xcassets/Card.imageset/Contents.json
  ClassManager/Assets.xcassets/Card.imageset/card.svg
  ClassManager/Assets.xcassets/Door.imageset/Contents.json
  ClassManager/Assets.xcassets/Door.imageset/door.svg
  ClassManager/Assets.xcassets/TabBarBackground.colorset/Contents.json
  ClassManager/ClassManagerApp.swift
  ClassManager/Extensions/Date.swift
  ClassManager/Extensions/Encodable.swift
  ClassManager/Helper/DataService.swift
  ClassManager/Model/Enrollment.swift
  ClassManager/Model/Student.swift
  ClassManager/View/ContainerView.swift
  ClassManager/View/PaymentStatusView.swift
  ClassManager/View/StudentInfoView.swift
Labels: 🌐 API, ⚙ feature, 🎨 UI, 🧑🏻‍💻 건

#35 클래스 휴강/삭제 처리 후 ClassCalendarView에 바로 반영되지 않는 버그 수정
  ClassManager/View/ClassCalendarView.swift
Labels: 🧑🏻‍💻 지오, 🔥 Hotfix

#37 QA 사항 반영
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Assets.xcassets/ChevronGray.colorset/Contents.json
  ClassManager/Assets.xcassets/ToastBackground.colorset/Contents.json
  ClassManager/Extensions/Date.swift
  ClassManager/Extensions/String.swift
  ClassManager/Reusable/ClassInfoBox.swift
  ClassManager/Reusable/Toast.swift
  ClassManager/View/AddClassView.swift
  ClassManager/View/AttendanceView.swift
  ClassManager/View/ClassCalendarView.swift
  ClassManager/View/ContainerView.swift
  ClassManager/View/CustomSearchBar.swift
  ClassManager/View/EditClassView.swift
  ClassManager/View/PaymentStatusView.swift
  ClassManager/View/StudentInfoView.swift
  ClassManager/View/SuspendView.swift
Labels: 🎨 UI, 🧑🏻‍💻 지오, 🔥 Hotfix

#38 Hotfix
  ClassManager/Helper/Constant.swift
  ClassManager/View/AddClassView.swift
  ClassManager/View/PaymentStatusView.swift
Labels: 🎨 UI, 🧑🏻‍💻 지오, 🔥 Hotfix

#41 런치 스크린 추가
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Assets.xcassets/Logo.imageset/Contents.json
  ClassManager/Assets.xcassets/Logo.imageset/Logo.png
  ClassManager/ClassManagerApp.swift
  ClassManager/View/ClassCalendarView.swift
  ClassManager/View/ContainerView.swift
  ClassManager/View/LaunchScreenView.swift
Labels: 🎨 UI, 🧑🏻‍💻 지오

#36 결제 현황 화면에서 이름이 가나다 순으로 나오도록 수정
  ClassManager/Helper/DataService.swift
Labels: 🐛 Debug, ⚙ feature, 🧑🏻‍💻 안토니

#42 버그 수정
  ClassManager/View/AttendanceView.swift
  ClassManager/View/ClassCalendarView.swift
Labels: 🧑🏻‍💻 지오, 🔥 Hotfix

#49 로그인 화면 및 자동 로그인 구현
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Helper/DataService.swift
  ClassManager/Model/Studio.swift
  ClassManager/View/LoginView.swift
Labels: 🌐 API, ⚙ feature, 🎨 UI, 🧑🏻‍💻 건

#50 수강생 정보에서 환불 여부/환불 사유 뷰 추가 및 기능 구현
  ClassManager/Helper/DataService.swift
  ClassManager/Model/Enrollment.swift
  ClassManager/View/AttendanceView.swift
  ClassManager/View/StudentInfoView.swift
Labels: 🌐 API, 🚧 Conflict, ⚙ feature, 🗃 Model, 🎨 UI, 🧑🏻‍💻 지오

#52 Firebase Function으로 카카오 알림톡 기능 구현
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Helper/DataService.swift
  ClassManager/View/AttendanceView.swift
  ClassManager/View/SuspendView.swift
Labels: 🌐 API, ⚙ feature, 📦 Package, 🧑🏻‍💻 안토니

#54 모델 변경
  ClassManager/Model/Student.swift
Labels: 🗃 Model, 🧑🏻‍💻 지오

#55 휴강시 쿠폰 자동 환불 처리
  ClassManager.xcodeproj/project.pbxproj
  ClassManager/Helper/DataService.swift
  ClassManager/Model/Coupon.swift
  ClassManager/Model/Student.swift
  ClassManager/View/StudentInfoView.swift
  ClassManager/View/SuspendView.swift
Labels: 🌐 API, ⚙ feature, 🗃 Model, 🧑🏻‍💻 지오

#56 환불 여부, 환불 사유 부분 사용성 개선
  ClassManager/Extensions/View.swift
  ClassManager/View/StudentInfoView.swift
Labels: ⚙ feature, 🎨 UI, 🧑🏻‍💻 지오
